"""resized to 300 user.photo

Revision ID: 5bb4f42633e3
Revises: 21925deae061
Create Date: 2021-05-02 14:39:10.301573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bb4f42633e3'
down_revision = '21925deae061'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
