"""resized to 300 user.photo

Revision ID: d558ba9f9103
Revises: 5bb4f42633e3
Create Date: 2021-05-02 14:41:07.623312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd558ba9f9103'
down_revision = '5bb4f42633e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
