"""add role to user serialisation

Revision ID: f5561d451579
Revises: d558ba9f9103
Create Date: 2021-05-20 16:21:07.083624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5561d451579'
down_revision = 'd558ba9f9103'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
